version: "3.9"
x-depends_on: &default-depends_on
  "db":
    condition: service_healthy
  "mail":
    condition: service_started

services:
  application:
    image: $ORO_IMAGE:$ORO_IMAGE_TAG
    command: -- true
    env_file:
      - .env
    depends_on:
      "web":
        condition: service_started
      "consumer":
        condition: service_started
      "cron":
        condition: service_started

  web:
    image: $ORO_IMAGE:$ORO_IMAGE_TAG
    command: nginx
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - target: 80
        published: 80
        mode: host
    depends_on:
      "php-fpm-app":
        condition: service_healthy
      "ws":
        condition: service_started
    volumes:
      - cache:/var/www/oro/var/cache:ro
      - public_storage:/var/www/oro/public/media:ro
      - private_storage:/var/www/oro/var/data:ro
    networks:
      default:
        aliases:
          - ${ORO_APP_DOMAIN}

  php-fpm-app:
    image: $ORO_IMAGE:$ORO_IMAGE_TAG
    command: php-fpm
    env_file:
      - .env
    healthcheck:
      test: "php-fpm-healthcheck"
      interval: 5s
      timeout: 30s
      start_period: 120s
    restart: unless-stopped
    depends_on:
      <<: *default-depends_on
    volumes:
      - cache:/var/www/oro/var/cache
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  ws:
    image: $ORO_IMAGE:$ORO_IMAGE_TAG
    command: console gos:websocket:server -v
    env_file:
      - .env
    restart: unless-stopped
    user: ${ORO_USER_RUNTIME:-www-data}
    init: true
    depends_on:
      "php-fpm-app":
        condition: service_healthy
    volumes:
      - cache:/var/www/oro/var/cache
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  consumer:
    image: $ORO_IMAGE:$ORO_IMAGE_TAG
    command: console oro:message-queue:consume --memory-limit=500 -v
    env_file:
      - .env
    restart: unless-stopped
    user: ${ORO_USER_RUNTIME:-www-data}
    init: true
    depends_on:
      "php-fpm-app":
        condition: service_healthy
    volumes:
      - cache:/var/www/oro/var/cache
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  cron:
    image: $ORO_IMAGE:$ORO_IMAGE_TAG
    command: cron
    env_file:
      - .env
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1024
        hard: 1048576
    depends_on:
      "php-fpm-app":
        condition: service_healthy
    volumes:
      - cache:/var/www/oro/var/cache
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  install:
    image: $ORO_IMAGE:$ORO_IMAGE_TAG
    command: console oro:install --no-interaction --timeout=3600 --user-name="$ORO_USER_NAME" --user-email="$ORO_USER_EMAIL" --user-firstname="$ORO_USER_FIRSTNAME" --user-lastname="$ORO_USER_LASTNAME" --user-password="$ORO_USER_PASSWORD" --sample-data="$ORO_SAMPLE_DATA" --organization-name="$ORO_ORGANIZATION_NAME" --language=$ORO_LANGUAGE --formatting-code=$ORO_FORMATTING_CODE --application-url="$ORO_APP_PROTOCOL://$ORO_APP_DOMAIN" $ORO_INSTALL_OPTIONS
    user: $ORO_USER_RUNTIME
    env_file:
      - .env
    depends_on:
      <<: *default-depends_on
    volumes:
      - cache:/var/www/oro/var/cache
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  restore: &restore
    image: ${ORO_IMAGE_INIT}${ORO_LANGUAGE_SUFFIX-}:$ORO_IMAGE_TAG
    command: restore
    user: $ORO_USER_RUNTIME
    env_file:
      - .env
    depends_on:
      <<: *default-depends_on
    volumes:
      - cache:/var/www/oro/var/cache
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  db:
    image: docker.io/oroinc/pgsql:${ORO_PG_VER}
    labels:
      com.symfony.server.service-prefix: ORO_DB
    environment:
      POSTGRES_ROOT_PASSWORD: ${ORO_DB_ROOT_PASSWORD}
      POSTGRES_DB: ${ORO_DB_NAME}
      POSTGRES_USER: ${ORO_DB_USER}
      POSTGRES_PASSWORD: ${ORO_DB_PASSWORD}
    healthcheck:
      test: "pg_isready -U$${POSTGRES_USER} -d$${POSTGRES_DB}"
      start_period: 60s
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  mail:
    image: mailhog/mailhog
    hostname: mail
    environment:
      MH_UI_WEB_PATH: mailcatcher
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /home/mailhog/maildir
    restart: unless-stopped

volumes:
  db_data: {}
  cache: {}
  public_storage: {}
  private_storage: {}
