apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Release.Name }}-consumer'
  labels:
    katenary.io/component: consumer
    katenary.io/path: .env
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 67b76b9b61f97b64634b3156d409f504f51a215d
    katenary.io/version: 2.0.0-beta2
data:
  ORO_APP_DOMAIN: orocommerce.p.zacharie.org
  ORO_APP_PROTOCOL: http
  ORO_DB_DSN: '"postgres://orodbuser:orodbpass@db:5432/orodb?sslmode=disable&charset=utf8&serverVersion=15.1"'
  ORO_DB_HOST: db
  ORO_DB_NAME: orodb
  ORO_DB_PASSWORD: orodbpass
  ORO_DB_PORT: "5432"
  ORO_DB_ROOT_PASSWORD: orodbpass
  ORO_DB_ROOT_USER: orodbuser
  ORO_DB_USER: orodbuser
  ORO_DB_VERSION: "15.1"
  ORO_ENV: prod
  ORO_FORMATTING_CODE: en_US
  ORO_IMAGE: oroinc/orocommerce-application
  ORO_IMAGE_INIT: ${ORO_IMAGE}-init
  ORO_IMAGE_TAG: 5.1.0
  ORO_INSTALL_OPTIONS: ""
  ORO_LANGUAGE: en
  ORO_MAILER_DSN: smtp://mail:1025
  ORO_MQ_DSN: 'dbal:'
  ORO_NGINX_HOST: web
  ORO_ORGANIZATION_NAME: ORO
  ORO_PG_VER: ${ORO_DB_VERSION}-alpine
  ORO_SAMPLE_DATA: "y"
  ORO_SEARCH_ENGINE_DSN: orm:?prefix=oro_search
  ORO_SESSION_DSN: 'native:'
  ORO_USER_EMAIL: admin@example.com
  ORO_USER_FIRSTNAME: John
  ORO_USER_LASTNAME: Doe
  ORO_USER_NAME: admin
  ORO_USER_PASSWORD: admin
  ORO_USER_RUNTIME: www-data
  ORO_WEBSITE_SEARCH_ENGINE_DSN: orm:?prefix=oro_website_search
  ORO_WEBSOCKET_BACKEND_DSN: tcp://ws:8080
  ORO_WEBSOCKET_FRONTEND_DSN: //*:80/ws
  ORO_WEBSOCKET_SERVER_DSN: //0.0.0.0:8080
  POSTGRES_DB: orodb
  POSTGRES_PASSWORD: orodbpass
  POSTGRES_ROOT_PASSWORD: orodbpass
  POSTGRES_USER: orodbuser
