{{ if .Values.cron.persistence.public_storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Release.Name }}-public_storage'
  labels:
    katenary.io/component: cron
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/pvc-name: public_storage
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 67b76b9b61f97b64634b3156d409f504f51a215d
    katenary.io/version: 2.0.0-beta2
spec:
  resources:
    requests:
      storage: '{{ .Values.cron.persistence.public_storage.capacity }}'
  accessModes:
    - ReadWriteOnce
{{- end -}}