apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-db'
  labels:
    katenary.io/component: db
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 67b76b9b61f97b64634b3156d409f504f51a215d
    katenary.io/version: 2.0.0-beta2
spec:
  selector:
    katenary.io/component: db
    katenary.io/release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
