apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-ws'
  labels:
    katenary.io/component: ws
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 67b76b9b61f97b64634b3156d409f504f51a215d
    katenary.io/version: 2.0.0-beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: ws
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: ws
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      initContainers:
        - name: check-php-fpm-app
          image: busybox
          command:
            - sh
            - -c
            - |-
              OK=0
              echo "Checking php-fpm-app port"
              while [ $OK != 1 ]; do
                  echo -n "."
                  nc -z {{ .Release.Name }}-php-fpm-app 9000 2>&1 >/dev/null && OK=1 || sleep 1
              done
              echo
              echo "Done"
      containers:
        - name: ws
          image: '{{ .Values.ws.repository.image }}{{ if ne .Values.ws.repository.tag "" }}:{{ .Values.ws.repository.tag }}{{ end }}'
          ports:
            - name: ws
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: '{{ .Release.Name }}-ws'
          command:
            - console
            - gos:websocket:server
            - -v
          volumeMounts:
            - mountPath: /var/www/oro/var/cache
              name: cache
            - mountPath: /var/www/oro/public/media
              name: public_storage
            - mountPath: /var/www/oro/var/data
              name: private_storage
      volumes:
        - name: cache
          {{- if  .Values.ws.persistence.cache.enabled }}
          persistentVolumeClaim:
            claimName: '{{ .Release.Name }}-cache'
          {{ else }}
          emptyDir: {}
          {{- end }}
        - name: public_storage
          {{- if  .Values.ws.persistence.public_storage.enabled }}
          persistentVolumeClaim:
            claimName: '{{ .Release.Name }}-public_storage'
          {{ else }}
          emptyDir: {}
          {{- end }}
        - name: private_storage
          {{- if  .Values.ws.persistence.private_storage.enabled }}
          persistentVolumeClaim:
            claimName: '{{ .Release.Name }}-private_storage'
          {{ else }}
          emptyDir: {}
          {{- end }}

