image:
  repository: oroinc/orocommerce-application
  tag: 5.1.0
  pullPolicy: IfNotPresent

additionalContainers:
  php-fpm:
    image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
    imagePullPolicy: IfNotPresent
    command: php-fpm
    resources:
        limits:
            cpu: 5000m
            ephemeral-storage: 1Gi
            memory: 5120Mi
        requests:
            cpu: 1000m
            ephemeral-storage: 1Gi
            memory: 1024Mi
    env:
      - name: ORO_APP_DOMAIN
        value: {{.Values.env.ORO_APP_DOMAIN}}
      - name: ORO_APP_PROTOCOL
        value: {{.Values.env.ORO_APP_PROTOCOL}}
      - name: ORO_FORMATTING_CODE
        value: {{.Values.env.ORO_FORMATTING_CODE}}
      - name: ORO_LANGUAGE
        value: {{.Values.env.ORO_LANGUAGE}}
      - name: ORO_NGINX_HOST
        value: {{.Values.env.ORO_NGINX_HOST}}
      - name: ORO_ORGANIZATION_NAME
        value: {{.Values.env.ORO_ORGANIZATION_NAME}}
      - name: ORO_SAMPLE_DATA
        value: {{.Values.env.ORO_SAMPLE_DATA}}
      - name: ORO_USER_EMAIL
        value: {{.Values.env.ORO_USER_EMAIL}}
      - name: ORO_USER_FIRSTNAME
        value: {{.Values.env.ORO_USER_FIRSTNAME}}
      - name: ORO_USER_LASTNAME
        value: {{.Values.env.ORO_USER_LASTNAME}}
      - name: ORO_USER_NAME
        value: {{.Values.env.ORO_USER_NAME}}
      - name: ORO_USER_PASSWORD
        value: {{.Values.env.ORO_USER_PASSWORD}}
      - name: TZ
        value: {{.Values.env.TZ}}

    volumeMounts:
      - name: cache
        mountPath: {{.Values.persistence.cache.mountPath}}
      - name: public_storage
        mountPath: {{.Values.persistence.public_storage.mountPath}}
      - name: private_storage
        mountPath: {{.Values.persistence.private_storage.mountPath}}
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000     

  ws:
    image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
    imagePullPolicy: IfNotPresent
    command: console gos:websocket:server -v
    resources:
        limits:
            cpu: 5000m
            ephemeral-storage: 1Gi
            memory: 5120Mi
        requests:
            cpu: 1000m
            ephemeral-storage: 1Gi
            memory: 1024Mi
    env:
      - name: ORO_APP_DOMAIN
        value: {{.Values.env.ORO_APP_DOMAIN}}
      - name: ORO_APP_PROTOCOL
        value: {{.Values.env.ORO_APP_PROTOCOL}}
      - name: ORO_FORMATTING_CODE
        value: {{.Values.env.ORO_FORMATTING_CODE}}
      - name: ORO_LANGUAGE
        value: {{.Values.env.ORO_LANGUAGE}}
      - name: ORO_NGINX_HOST
        value: {{.Values.env.ORO_NGINX_HOST}}
      - name: ORO_ORGANIZATION_NAME
        value: {{.Values.env.ORO_ORGANIZATION_NAME}}
      - name: ORO_SAMPLE_DATA
        value: {{.Values.env.ORO_SAMPLE_DATA}}
      - name: ORO_USER_EMAIL
        value: {{.Values.env.ORO_USER_EMAIL}}
      - name: ORO_USER_FIRSTNAME
        value: {{.Values.env.ORO_USER_FIRSTNAME}}
      - name: ORO_USER_LASTNAME
        value: {{.Values.env.ORO_USER_LASTNAME}}
      - name: ORO_USER_NAME
        value: {{.Values.env.ORO_USER_NAME}}
      - name: ORO_USER_PASSWORD
        value: {{.Values.env.ORO_USER_PASSWORD}}
      - name: TZ
        value: {{.Values.env.TZ}}
    volumeMounts:
      - name: cache
        mountPath: {{.Values.persistence.cache.mountPath}}
      - name: public_storage
        mountPath: {{.Values.persistence.public_storage.mountPath}}
      - name: private_storage
        mountPath: {{.Values.persistence.private_storage.mountPath}}

    securityContext:
      runAsUser: 1000
      runAsGroup: 1000     

env:
  TZ: UTC
  ORO_USER_NAME: admin
  ORO_USER_PASSWORD: admin
  ORO_USER_FIRSTNAME: John
  ORO_USER_LASTNAME: Doe
  ORO_USER_EMAIL: admin@example.com
  ORO_SAMPLE_DATA: y
  ORO_ORGANIZATION_NAME: ORO
  ORO_LANGUAGE: en
  ORO_FORMATTING_CODE: en_US
  ORO_APP_PROTOCOL: http
  ORO_APP_DOMAIN: oro.demo
  ORO_NGINX_HOST: web
  #ORO_INSTALL_OPTIONS=

service:
  main:
    ports:
      http:
        port: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

persistence:
  cache:
    enabled: true
    mountPath: /var/www/oro/var/cache
    accessMode: ReadWriteMany
    size: 1Gb
  public_storage:
    enabled: true
    mountPath: /var/www/oro/public/media
    accessMode: ReadWriteMany
    size: 1Gb
  private_storage:
    enabled: true
    mountPath: /var/www/oro/var/data
    accessMode: ReadWriteMany
    size: 1Gb
  
config:
  nginx-server.conf: {}

  php-settings.ini: {}

  php-fpm-server.conf: {}
