apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oro-postgres-sbx
  namespace: argo-cd
spec:
  destination:
    namespace: oro-sbx
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: postgresql
    helm:
      values: |-
        global:
          postgresql:
            auth:
              postgresPassword: "orocommerce"
              username: "orocommerce"
              password: "orocommerce"
              database: "orocommerce"
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.2.6
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
