{{ if .Values.consumer.persistence.private_storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Release.Name }}-private_storage'
  labels:
    katenary.io/component: consumer
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/pvc-name: private_storage
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 26eb54535aff4cf701c2177e321811281ffb9a01
    katenary.io/version: 2.0.0-beta2
spec:
  resources:
    requests:
      storage: '{{ .Values.consumer.persistence.private_storage.capacity }}'
  accessModes:
    - ReadWriteOnce
{{- end -}}