apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-consumer'
  labels:
    katenary.io/component: consumer
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 26eb54535aff4cf701c2177e321811281ffb9a01
    katenary.io/version: 2.0.0-beta2
spec:
  selector:
    katenary.io/component: consumer
    katenary.io/release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
