{{ if .Values.db.persistence.db_data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Release.Name }}-db_data'
  labels:
    katenary.io/component: db
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/pvc-name: db_data
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 26eb54535aff4cf701c2177e321811281ffb9a01
    katenary.io/version: 2.0.0-beta2
spec:
  resources:
    requests:
      storage: '{{ .Values.db.persistence.db_data.capacity }}'
  accessModes:
    - ReadWriteOnce
{{- end -}}