apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-web'
  labels:
    katenary.io/component: web
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 26eb54535aff4cf701c2177e321811281ffb9a01
    katenary.io/version: 2.0.0-beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: web
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: web
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      initContainers:
        - name: check-php-fpm-app
          image: busybox
          command:
            - sh
            - -c
            - |-
              OK=0
              echo "Checking php-fpm-app port"
              while [ $OK != 1 ]; do
                  echo -n "."
                  nc -z {{ .Release.Name }}-php-fpm-app 9000 2>&1 >/dev/null && OK=1 || sleep 1
              done
              echo
              echo "Done"
        - name: check-ws
          image: busybox
          command:
            - sh
            - -c
            - |-
              OK=0
              echo "Checking ws port"
              while [ $OK != 1 ]; do
                  echo -n "."
                  nc -z {{ .Release.Name }}-ws 8080 2>&1 >/dev/null && OK=1 || sleep 1
              done
              echo
              echo "Done"
      containers:
        - name: web
          image: '{{ .Values.web.repository.image }}{{ if ne .Values.web.repository.tag "" }}:{{ .Values.web.repository.tag }}{{ end }}'
          ports:
            - name: web
              containerPort: 80
          envFrom:
            - configMapRef:
                name: '{{ .Release.Name }}-web'
          command:
            - nginx
          volumeMounts:
            - mountPath: /var/www/oro/var/cache
              name: cache
            - mountPath: /var/www/oro/public/media
              name: public_storage
            - mountPath: /var/www/oro/var/data
              name: private_storage
      volumes:
        - name: cache
          {{- if  .Values.web.persistence.cache.enabled }}
          persistentVolumeClaim:
            claimName: '{{ .Release.Name }}-cache'
          {{ else }}
          emptyDir: {}
          {{- end }}
        - name: public_storage
          {{- if  .Values.web.persistence.public_storage.enabled }}
          persistentVolumeClaim:
            claimName: '{{ .Release.Name }}-public_storage'
          {{ else }}
          emptyDir: {}
          {{- end }}
        - name: private_storage
          {{- if  .Values.web.persistence.private_storage.enabled }}
          persistentVolumeClaim:
            claimName: '{{ .Release.Name }}-private_storage'
          {{ else }}
          emptyDir: {}
          {{- end }}

