{{ if .Values.ws.persistence.cache.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Release.Name }}-cache'
  labels:
    katenary.io/component: ws
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/pvc-name: cache
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 26eb54535aff4cf701c2177e321811281ffb9a01
    katenary.io/version: 2.0.0-beta2
spec:
  resources:
    requests:
      storage: '{{ .Values.ws.persistence.cache.capacity }}'
  accessModes:
    - ReadWriteOnce
{{- end -}}